# Generated by Django 2.0.2 on 2018-03-16 16:50

from django.db import migrations
from wagtail.core.rich_text import RichText
from wagtail.core.blocks import StreamValue


def convert_to_streamfield(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    for page in BlogPage.objects.all():
        print('BODY', type(page.body), RichText(page.body))
        if page.body:
            page.body = [('rich_text', RichText(page.body))]
            page.save()
            print('PAGE_SAVED', page.body)


def convert_to_richtext(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    print('TEST123')
    for page in BlogPage.objects.all():
        if page.body.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in page.body
                if child.block_type == 'rich_text'
            ])
            page.body = raw_text
            page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180206_2239'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
